// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevTech.Data;

#nullable disable

namespace RevTech.Data.Migrations
{
    [DbContext(typeof(RevtechDbContext))]
    [Migration("20230702112952_SeedDBWithECUAndTCU")]
    partial class SeedDBWithECUAndTCU
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.ECU_TCU_ConnectionTable", b =>
                {
                    b.Property<int>("ECUTuningId")
                        .HasColumnType("int");

                    b.Property<int>("TCUTuningId")
                        .HasColumnType("int");

                    b.HasKey("ECUTuningId", "TCUTuningId");

                    b.HasIndex("TCUTuningId");

                    b.ToTable("ECU_TCU_Connection");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.ECUTuning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("HorsePowerBoost")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TorqueBoost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.ToTable("ECUTunings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EngineId = 1,
                            HorsePowerBoost = 45,
                            ImageURL = "https://motoristprod.s3.amazonaws.com/uploads/redactor_rails/picture/data/3244/motorist-ecu-tuning-june-2020.png",
                            Manufacturer = "Quantum Tuning",
                            Name = "ECU Upgrade for 1.8t",
                            Price = 150.0m,
                            TorqueBoost = 100
                        },
                        new
                        {
                            Id = 2,
                            EngineId = 2,
                            HorsePowerBoost = 45,
                            ImageURL = "https://motoristprod.s3.amazonaws.com/uploads/redactor_rails/picture/data/3244/motorist-ecu-tuning-june-2020.png",
                            Manufacturer = "Quantum Tuning",
                            Name = "ECU Upgrade for 1.8t",
                            Price = 150.0m,
                            TorqueBoost = 100
                        },
                        new
                        {
                            Id = 3,
                            EngineId = 3,
                            HorsePowerBoost = 45,
                            ImageURL = "https://motoristprod.s3.amazonaws.com/uploads/redactor_rails/picture/data/3244/motorist-ecu-tuning-june-2020.png",
                            Manufacturer = "Quantum Tuning",
                            Name = "ECU Upgrade for 1.8t",
                            Price = 150.0m,
                            TorqueBoost = 100
                        },
                        new
                        {
                            Id = 4,
                            EngineId = 4,
                            HorsePowerBoost = 65,
                            ImageURL = "https://www.034motorsport.com/media/fishpig/webp/catalog/product/cache/1151afdc91a7a37549ca32dea82af8c6/b/5/b5_s4_stage1.webp",
                            Manufacturer = "034Motorsport",
                            Name = "ECU Upgrade for 2.7t",
                            Price = 495.0m,
                            TorqueBoost = 90
                        },
                        new
                        {
                            Id = 5,
                            EngineId = 5,
                            HorsePowerBoost = 65,
                            ImageURL = "https://www.034motorsport.com/media/fishpig/webp/catalog/product/cache/1151afdc91a7a37549ca32dea82af8c6/b/5/b5_s4_stage1.webp",
                            Manufacturer = "034Motorsport",
                            Name = "ECU Upgrade for 2.7t",
                            Price = 495.0m,
                            TorqueBoost = 90
                        },
                        new
                        {
                            Id = 6,
                            EngineId = 6,
                            HorsePowerBoost = 10,
                            ImageURL = "https://images.goapr.com/583x/apr_ecu.png",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 4.2 FSI",
                            Price = 499.95m,
                            TorqueBoost = 50
                        },
                        new
                        {
                            Id = 7,
                            EngineId = 7,
                            HorsePowerBoost = 10,
                            ImageURL = "https://images.goapr.com/583x/apr_ecu.png",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 4.2 FSI",
                            Price = 499.95m,
                            TorqueBoost = 50
                        },
                        new
                        {
                            Id = 8,
                            EngineId = 8,
                            HorsePowerBoost = 10,
                            ImageURL = "https://images.goapr.com/583x/apr_ecu.png",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 4.2 FSI",
                            Price = 499.95m,
                            TorqueBoost = 50
                        },
                        new
                        {
                            Id = 9,
                            EngineId = 9,
                            HorsePowerBoost = 55,
                            ImageURL = "https://images.goapr.com/583x/apr_ecu.png",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 2.0 TFSI",
                            Price = 399.95m,
                            TorqueBoost = 70
                        },
                        new
                        {
                            Id = 10,
                            EngineId = 10,
                            HorsePowerBoost = 55,
                            ImageURL = "https://images.goapr.com/583x/apr_ecu.png",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 2.0 TFSI",
                            Price = 399.95m,
                            TorqueBoost = 70
                        },
                        new
                        {
                            Id = 11,
                            EngineId = 11,
                            HorsePowerBoost = 130,
                            ImageURL = "https://clptuning.co.uk/wp-content/uploads/2016/11/APR-Stage-1-300x300.jpg",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 4.0 TFSI",
                            Price = 1200.00m,
                            TorqueBoost = 180
                        },
                        new
                        {
                            Id = 12,
                            EngineId = 12,
                            HorsePowerBoost = 80,
                            ImageURL = "https://images.goapr.com/583x/apr_ecu.png",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 4.0 TFSI",
                            Price = 800.00m,
                            TorqueBoost = 130
                        },
                        new
                        {
                            Id = 13,
                            EngineId = 13,
                            HorsePowerBoost = 80,
                            ImageURL = "https://images.goapr.com/583x/apr_ecu.png",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 4.0 TFSI",
                            Price = 800.00m,
                            TorqueBoost = 130
                        },
                        new
                        {
                            Id = 14,
                            EngineId = 14,
                            HorsePowerBoost = 120,
                            ImageURL = "http://www.goapr.co.uk/includes/img/icons/apr-ecu.png",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 3.0 TFSI",
                            Price = 900.00m,
                            TorqueBoost = 70
                        },
                        new
                        {
                            Id = 15,
                            EngineId = 15,
                            HorsePowerBoost = 120,
                            ImageURL = "http://www.goapr.co.uk/includes/img/icons/apr-ecu.png",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 3.0 TFSI",
                            Price = 900.00m,
                            TorqueBoost = 70
                        },
                        new
                        {
                            Id = 16,
                            EngineId = 16,
                            HorsePowerBoost = 120,
                            ImageURL = "http://www.goapr.co.uk/includes/img/icons/apr-ecu.png",
                            Manufacturer = "APR",
                            Name = "ECU Upgrade for 3.0 TFSI",
                            Price = 900.00m,
                            TorqueBoost = 70
                        });
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.ExhaustKit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("HorsePowerBoost")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TorqueBoost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.ToTable("ExhaustKits");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.FuelPump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("HorsePowerBoost")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TorqueBoost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.ToTable("FuelPumps");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.InjectorKit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("HorsePowerBoost")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TorqueBoost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.ToTable("InjectorKits");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.OilCooler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.ToTable("OilCoolers");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.SparkPlugs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PriceForKit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.ToTable("SparkPlugsKits");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.SuperchargerKit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("HorsePowerBoost")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TorqueBoost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.ToTable("SuperchargerKits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EngineId = 6,
                            HorsePowerBoost = 200,
                            ImageURL = "http://goapr.jp/includes/img/products/stage_3+_b7rs4_kit_mid.jpg",
                            Manufacturer = "APR",
                            ModelName = "TVS1740 Stage 3+",
                            Price = 18000.99m,
                            TorqueBoost = 210
                        },
                        new
                        {
                            Id = 2,
                            EngineId = 7,
                            HorsePowerBoost = 180,
                            ImageURL = "http://www.goapr.co.uk/includes/img/products/b8_s5_42l_stage_3_kit_mid.jpg",
                            Manufacturer = "APR",
                            ModelName = "95 RON",
                            Price = 17000.99m,
                            TorqueBoost = 140
                        },
                        new
                        {
                            Id = 3,
                            EngineId = 8,
                            HorsePowerBoost = 180,
                            ImageURL = "https://fr-rtuning-shop.co.uk/images/cache/pes_supercharger.270.jpg",
                            Manufacturer = "PES",
                            ModelName = "Whipple 140AX",
                            Price = 15000.99m,
                            TorqueBoost = 140
                        },
                        new
                        {
                            Id = 4,
                            EngineId = 13,
                            HorsePowerBoost = 120,
                            ImageURL = "https://fr-rtuning-shop.co.uk/images/cache/pes_supercharger.270.jpg",
                            Manufacturer = "CNC",
                            ModelName = "Ported",
                            Price = 2099.70m,
                            TorqueBoost = 100
                        },
                        new
                        {
                            Id = 5,
                            EngineId = 14,
                            HorsePowerBoost = 120,
                            ImageURL = "https://fr-rtuning-shop.co.uk/images/cache/pes_supercharger.270.jpg",
                            Manufacturer = "CNC",
                            ModelName = "Ported",
                            Price = 2099.70m,
                            TorqueBoost = 100
                        },
                        new
                        {
                            Id = 6,
                            EngineId = 15,
                            HorsePowerBoost = 120,
                            ImageURL = "https://fr-rtuning-shop.co.uk/images/cache/pes_supercharger.270.jpg",
                            Manufacturer = "CNC",
                            ModelName = "Ported",
                            Price = 2099.70m,
                            TorqueBoost = 100
                        });
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.TCUTuning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TCUTunings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Once this selected TCU Option is installed, it will result in a higher Top Speed, but the acceleration rate will be reduced",
                            ImageURL = "https://tuitionphysics.com/wp-content/uploads/2020/06/speed-velocity-and-acceleration-concepts-differences.jpg",
                            Name = "Increase Top Speed"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Once this selected TCU Option is installed, it will result in a faster Acceleration, but the Top Speed will be reduced",
                            ImageURL = "https://grimmermotors.co.nz/wp-content/uploads/2018/03/high-rpm.jpg",
                            Name = "Increase Acceleration"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This TCU Option includes a balanced combination of both Acceleration and Top Speed",
                            ImageURL = "https://cdn.hswstatic.com/gif/gears-1.jpg",
                            Name = "Balanced"
                        });
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.TurboKit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("HorsePowerBoost")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("PressureBoost")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TorqueBoost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.ToTable("TurboKits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EngineId = 1,
                            HorsePowerBoost = 200,
                            ImageURL = "https://www.turbozentrum.de/media/image/product/826/lg/garrett-turbokit-vw-golf-bora-audi-a3-tt-18t-350ps.jpg",
                            Manufacturer = "Garrett",
                            ModelName = "GT2860RS",
                            PressureBoost = 1.8m,
                            Price = 2799.67m,
                            TorqueBoost = 250
                        },
                        new
                        {
                            Id = 2,
                            EngineId = 1,
                            HorsePowerBoost = 160,
                            ImageURL = "https://www.bar-tek-tuning.com/cdn-cgi/image/fit=scale-down,quality=50,sharpen=1,format=auto,width=1920/https://www.bar-tek-tuning.com/thumbnail/fe/88/79/1683873716/2218t03-1.8T%20Tuning-Kit%20STUFE%203_1920x1920.webp",
                            Manufacturer = "BAR-TEK",
                            ModelName = "Turbo-Total K04-001",
                            PressureBoost = 1.6m,
                            Price = 2115.26m,
                            TorqueBoost = 200
                        },
                        new
                        {
                            Id = 3,
                            EngineId = 2,
                            HorsePowerBoost = 280,
                            ImageURL = "https://www.raimotorsport.com/v/vspfiles/photos/RAI_B6A4_1.8t_GTX-2.jpg",
                            Manufacturer = "RAI",
                            ModelName = "GTX B6A4",
                            PressureBoost = 2.0m,
                            Price = 2675.00m,
                            TorqueBoost = 310
                        },
                        new
                        {
                            Id = 4,
                            EngineId = 2,
                            HorsePowerBoost = 210,
                            ImageURL = "https://turboconcepts.net/wp-content/uploads/2019/11/A4_18t_long_blackfridaypackage.gif",
                            Manufacturer = "RAI",
                            ModelName = "Turbo Concepts",
                            PressureBoost = 1.9m,
                            Price = 1679.00m,
                            TorqueBoost = 270
                        },
                        new
                        {
                            Id = 5,
                            EngineId = 3,
                            HorsePowerBoost = 190,
                            ImageURL = "https://www.turbo-parts.de/images/product_images/info_images/1.8T%20mit%20Downpipe.jpg",
                            Manufacturer = "Garrett",
                            ModelName = "GT2876R",
                            PressureBoost = 1.8m,
                            Price = 1851.98m,
                            TorqueBoost = 250
                        },
                        new
                        {
                            Id = 6,
                            EngineId = 4,
                            HorsePowerBoost = 400,
                            ImageURL = "https://turboconcepts.net/wp-content/uploads/2019/11/DZX-274a.gif",
                            Manufacturer = "Turbo Concepts",
                            ModelName = "DZX-274",
                            PressureBoost = 2.2m,
                            Price = 1995.00m,
                            TorqueBoost = 500
                        },
                        new
                        {
                            Id = 7,
                            EngineId = 4,
                            HorsePowerBoost = 400,
                            ImageURL = "https://www.034motorsport.com/media/fishpig/webp/catalog/product/cache/1151afdc91a7a37549ca32dea82af8c6/0/3/034Motorsport_B5_S4_RS4_K04_Stage_3_Turbo_Kit_1.webp",
                            Manufacturer = "034Motorsport",
                            ModelName = "K04 Twin Turbo",
                            PressureBoost = 2.3m,
                            Price = 3671.90m,
                            TorqueBoost = 500
                        },
                        new
                        {
                            Id = 8,
                            EngineId = 5,
                            HorsePowerBoost = 380,
                            ImageURL = "https://www.tzr-motorsport.de/WebRoot/Store20/Shops/61911476/5F43/7DE0/D7D2/230B/A266/0A0C/6D10/D0F0/TTE380_Turbolader_Audi_A6_C5_TZR_Motorsport.jpg",
                            Manufacturer = "The Turbo Engineers",
                            ModelName = "TTE380+",
                            PressureBoost = 2.1m,
                            Price = 2723.50m,
                            TorqueBoost = 450
                        },
                        new
                        {
                            Id = 9,
                            EngineId = 9,
                            HorsePowerBoost = 250,
                            ImageURL = "https://shop.gmcracing.com/1161-large_default/turbo-kit-audivw-20-tfsi-for-powers-up-to-450hp-with-tial-recirculation-wastegate.jpg",
                            Manufacturer = "GMC Racing",
                            ModelName = "GMC0501KT",
                            PressureBoost = 1.9m,
                            Price = 4182.85m,
                            TorqueBoost = 300
                        },
                        new
                        {
                            Id = 10,
                            EngineId = 9,
                            HorsePowerBoost = 180,
                            ImageURL = "https://shop.gmcracing.com/1161-large_default/turbo-kit-audivw-20-tfsi-for-powers-up-to-450hp-with-tial-recirculation-wastegate.jpg",
                            Manufacturer = "BAR-TEK",
                            ModelName = "Tuning-Kit K04",
                            PressureBoost = 1.8m,
                            Price = 2733.32m,
                            TorqueBoost = 250
                        },
                        new
                        {
                            Id = 11,
                            EngineId = 9,
                            HorsePowerBoost = 150,
                            ImageURL = "https://www.tte24.net/images/product_images/info_images/1130_0.JPG",
                            Manufacturer = "The Turbo Engineers",
                            ModelName = "TTE450",
                            PressureBoost = 1.8m,
                            Price = 1902.43m,
                            TorqueBoost = 220
                        },
                        new
                        {
                            Id = 12,
                            EngineId = 10,
                            HorsePowerBoost = 250,
                            ImageURL = "https://shop.gmcracing.com/1161-large_default/turbo-kit-audivw-20-tfsi-for-powers-up-to-450hp-with-tial-recirculation-wastegate.jpg",
                            Manufacturer = "GMC Racing",
                            ModelName = "GMC0501KT",
                            PressureBoost = 1.9m,
                            Price = 4182.85m,
                            TorqueBoost = 300
                        },
                        new
                        {
                            Id = 13,
                            EngineId = 10,
                            HorsePowerBoost = 180,
                            ImageURL = "https://shop.gmcracing.com/1161-large_default/turbo-kit-audivw-20-tfsi-for-powers-up-to-450hp-with-tial-recirculation-wastegate.jpg",
                            Manufacturer = "BAR-TEK",
                            ModelName = "Tuning-Kit K04",
                            PressureBoost = 1.8m,
                            Price = 2733.32m,
                            TorqueBoost = 250
                        },
                        new
                        {
                            Id = 14,
                            EngineId = 10,
                            HorsePowerBoost = 150,
                            ImageURL = "https://www.tte24.net/images/product_images/info_images/1130_0.JPG",
                            Manufacturer = "The Turbo Engineers",
                            ModelName = "TTE450",
                            PressureBoost = 1.8m,
                            Price = 1902.43m,
                            TorqueBoost = 220
                        },
                        new
                        {
                            Id = 15,
                            EngineId = 11,
                            HorsePowerBoost = 240,
                            ImageURL = "https://tteglobal.com/media/image/f7/0f/4d/TTE800-2_600x600.jpg",
                            Manufacturer = "The Turbo Engineers",
                            ModelName = "TTE800+",
                            PressureBoost = 2.2m,
                            Price = 2788.04m,
                            TorqueBoost = 280
                        },
                        new
                        {
                            Id = 16,
                            EngineId = 12,
                            HorsePowerBoost = 240,
                            ImageURL = "https://tteglobal.com/media/image/f7/0f/4d/TTE800-2_600x600.jpg",
                            Manufacturer = "The Turbo Engineers",
                            ModelName = "TTE800+",
                            PressureBoost = 2.2m,
                            Price = 2788.04m,
                            TorqueBoost = 280
                        },
                        new
                        {
                            Id = 17,
                            EngineId = 13,
                            HorsePowerBoost = 240,
                            ImageURL = "https://tteglobal.com/media/image/f7/0f/4d/TTE800-2_600x600.jpg",
                            Manufacturer = "The Turbo Engineers",
                            ModelName = "TTE800+",
                            PressureBoost = 2.2m,
                            Price = 2788.04m,
                            TorqueBoost = 280
                        },
                        new
                        {
                            Id = 18,
                            EngineId = 11,
                            HorsePowerBoost = 180,
                            ImageURL = "https://cdn.shopify.com/s/files/1/0451/1340/9690/products/DSC02364_1800x1800.jpg?v=1613506907",
                            Manufacturer = "HPA Motorsports",
                            ModelName = "HVA-246",
                            PressureBoost = 2.2m,
                            Price = 1799.00m,
                            TorqueBoost = 240
                        },
                        new
                        {
                            Id = 19,
                            EngineId = 12,
                            HorsePowerBoost = 180,
                            ImageURL = "https://cdn.shopify.com/s/files/1/0451/1340/9690/products/DSC02364_1800x1800.jpg?v=1613506907",
                            Manufacturer = "HPA Motorsports",
                            ModelName = "HVA-246",
                            PressureBoost = 2.2m,
                            Price = 1799.00m,
                            TorqueBoost = 240
                        },
                        new
                        {
                            Id = 20,
                            EngineId = 13,
                            HorsePowerBoost = 180,
                            ImageURL = "https://cdn.shopify.com/s/files/1/0451/1340/9690/products/DSC02364_1800x1800.jpg?v=1613506907",
                            Manufacturer = "HPA Motorsports",
                            ModelName = "HVA-246",
                            PressureBoost = 2.2m,
                            Price = 1799.00m,
                            TorqueBoost = 240
                        },
                        new
                        {
                            Id = 21,
                            EngineId = 11,
                            HorsePowerBoost = 195,
                            ImageURL = "https://static.wixstatic.com/media/16bf23_ed5ccc9846734ceca77e1d91994b4ef4~mv2_d_2000_1333_s_2.jpg/v1/fill/w_938,h_700,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/16bf23_ed5ccc9846734ceca77e1d91994b4ef4~mv2_d_2000_1333_s_2.jpg",
                            Manufacturer = "Turbo Systems",
                            ModelName = "TSUTRSV2",
                            PressureBoost = 2.2m,
                            Price = 2137.50m,
                            TorqueBoost = 280
                        },
                        new
                        {
                            Id = 22,
                            EngineId = 12,
                            HorsePowerBoost = 195,
                            ImageURL = "https://static.wixstatic.com/media/16bf23_ed5ccc9846734ceca77e1d91994b4ef4~mv2_d_2000_1333_s_2.jpg/v1/fill/w_938,h_700,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/16bf23_ed5ccc9846734ceca77e1d91994b4ef4~mv2_d_2000_1333_s_2.jpg",
                            Manufacturer = "Turbo Systems",
                            ModelName = "TSUTRSV2",
                            PressureBoost = 2.2m,
                            Price = 2137.50m,
                            TorqueBoost = 280
                        },
                        new
                        {
                            Id = 23,
                            EngineId = 13,
                            HorsePowerBoost = 195,
                            ImageURL = "https://static.wixstatic.com/media/16bf23_ed5ccc9846734ceca77e1d91994b4ef4~mv2_d_2000_1333_s_2.jpg/v1/fill/w_938,h_700,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/16bf23_ed5ccc9846734ceca77e1d91994b4ef4~mv2_d_2000_1333_s_2.jpg",
                            Manufacturer = "Turbo Systems",
                            ModelName = "TSUTRSV2",
                            PressureBoost = 2.2m,
                            Price = 2137.50m,
                            TorqueBoost = 280
                        },
                        new
                        {
                            Id = 24,
                            EngineId = 13,
                            HorsePowerBoost = 395,
                            ImageURL = "https://www.tte24.net/images/product_images/popup_images/1272_1.JPG",
                            Manufacturer = "The Turbo Engineers",
                            ModelName = "TTE1000+ Hybrid",
                            PressureBoost = 2.5m,
                            Price = 8745.71m,
                            TorqueBoost = 450
                        });
                });

            modelBuilder.Entity("RevTech.Data.Models.UserConfiguration.UserConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<int?>("ECUTuningId")
                        .HasColumnType("int");

                    b.Property<int?>("ExhaustKitId")
                        .HasColumnType("int");

                    b.Property<int?>("FuelPumpId")
                        .HasColumnType("int");

                    b.Property<int>("HorsePowerBoostTotal")
                        .HasColumnType("int");

                    b.Property<int?>("InjectorKitId")
                        .HasColumnType("int");

                    b.Property<int?>("OilCoolerId")
                        .HasColumnType("int");

                    b.Property<int?>("SparkPlugsId")
                        .HasColumnType("int");

                    b.Property<int?>("SuperchargerKitId")
                        .HasColumnType("int");

                    b.Property<int?>("TCUTuningId")
                        .HasColumnType("int");

                    b.Property<int>("TorqueBoostTotal")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TurboKitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.HasIndex("ECUTuningId");

                    b.HasIndex("ExhaustKitId");

                    b.HasIndex("FuelPumpId");

                    b.HasIndex("InjectorKitId");

                    b.HasIndex("OilCoolerId");

                    b.HasIndex("SparkPlugsId");

                    b.HasIndex("SuperchargerKitId");

                    b.HasIndex("TCUTuningId");

                    b.HasIndex("TurboKitId");

                    b.ToTable("UsersConfigurations");
                });

            modelBuilder.Entity("RevTech.Data.Models.Vehicles.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("YearCreated_End")
                        .HasColumnType("int");

                    b.Property<int>("YearCreated_Start")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageURL = "https://img.favcars.com/audi/a6/photos_audi_a6_2001_2_b.jpg",
                            ManufacturerId = 1,
                            ModelName = "A6 C5",
                            YearCreated_End = 2004,
                            YearCreated_Start = 1997
                        },
                        new
                        {
                            Id = 2,
                            ImageURL = "https://i.ytimg.com/vi/AAfmxSRncBU/maxresdefault.jpg",
                            ManufacturerId = 1,
                            ModelName = "A4 B5",
                            YearCreated_End = 2001,
                            YearCreated_Start = 1996
                        },
                        new
                        {
                            Id = 3,
                            ImageURL = "https://stillrunningstrong.com/wp-content/uploads/2018/03/Audi-A4-b6-sport-model-S4-1024x466.jpg",
                            ManufacturerId = 1,
                            ModelName = "A4 B6",
                            YearCreated_End = 2004,
                            YearCreated_Start = 2002
                        },
                        new
                        {
                            Id = 4,
                            ImageURL = "https://images.fitmentindustries.com/web-compressed/1740944-1-2001-s4-audi-base-bc-racing-coilovers-bbs-ch-r-silver.jpg",
                            ManufacturerId = 1,
                            ModelName = "S4 B5",
                            YearCreated_End = 2001,
                            YearCreated_Start = 1997
                        },
                        new
                        {
                            Id = 5,
                            ImageURL = "https://media.evo.co.uk/image/private/s--zWq7JwVH--/v1556260759/evo/images/dir_688/car_photo_344347.jpg",
                            ManufacturerId = 1,
                            ModelName = "RS4 B7",
                            YearCreated_End = 2009,
                            YearCreated_Start = 2005
                        },
                        new
                        {
                            Id = 6,
                            ImageURL = "https://www.ast-suspension.com/imager/common/10988/Audi-S5-B8-3_ccc647699d3b878f33fab0fc43e2f880.jpg",
                            ManufacturerId = 1,
                            ModelName = "S5 B8",
                            YearCreated_End = 2013,
                            YearCreated_Start = 2007
                        },
                        new
                        {
                            Id = 7,
                            ImageURL = "https://en.audiclub.eu/graphics/gallery/full/2178_13237385133-509f54d839-b.jpg",
                            ManufacturerId = 1,
                            ModelName = "S5 B8.5",
                            YearCreated_End = 2017,
                            YearCreated_Start = 2013
                        },
                        new
                        {
                            Id = 8,
                            ImageURL = "https://cimg7.ibsrv.net/gimg/www.audiworld.com-vbulletin/1200x837/audi_driveway_725b6dcf65369cb5d7d45810f3e5e8d8c487097a.jpg",
                            ManufacturerId = 1,
                            ModelName = "RS5 B8.5",
                            YearCreated_End = 2017,
                            YearCreated_Start = 2013
                        },
                        new
                        {
                            Id = 9,
                            ImageURL = "https://cdn.shopify.com/s/files/1/0570/5518/3000/collections/a6_c6.jpg?v=1648793950",
                            ManufacturerId = 1,
                            ModelName = "A6 C6",
                            YearCreated_End = 2011,
                            YearCreated_Start = 2004
                        },
                        new
                        {
                            Id = 10,
                            ImageURL = "https://i.pinimg.com/originals/e1/a2/32/e1a232889a2009dffca15f9b432ab3b8.jpg",
                            ManufacturerId = 1,
                            ModelName = "A4 B7",
                            YearCreated_End = 2008,
                            YearCreated_Start = 2004
                        },
                        new
                        {
                            Id = 11,
                            ImageURL = "https://i.pinimg.com/originals/4f/54/ea/4f54ea4597e4fc876df08c49bad03992.jpg",
                            ManufacturerId = 1,
                            ModelName = "A4 B8.5",
                            YearCreated_End = 2015,
                            YearCreated_Start = 2012
                        },
                        new
                        {
                            Id = 12,
                            ImageURL = "https://img.md-exclusive-cardesign.com/wp-content/uploads/2019/10/audi-a6-c7-limousine-breitbau-tuning-pd600r-widebody-kit-artform-af-401-felgen-in-105x21-md-exclusive-cardesign-16-455x179.jpg",
                            ManufacturerId = 1,
                            ModelName = "S6 C7",
                            YearCreated_End = 2018,
                            YearCreated_Start = 2011
                        },
                        new
                        {
                            Id = 13,
                            ImageURL = "https://img.md-exclusive-cardesign.com/wp-content/uploads/2019/10/audi-a6-c7-limousine-breitbau-tuning-pd600r-widebody-kit-artform-af-401-felgen-in-105x21-md-exclusive-cardesign-16-455x179.jpg",
                            ManufacturerId = 1,
                            ModelName = "RS6 C7",
                            YearCreated_End = 2018,
                            YearCreated_Start = 2011
                        },
                        new
                        {
                            Id = 14,
                            ImageURL = "https://www.tuning.bg/public/upload/gallery/extended/normal/1358582002.jpg",
                            ManufacturerId = 1,
                            ModelName = "S8 D4",
                            YearCreated_End = 2015,
                            YearCreated_Start = 2012
                        },
                        new
                        {
                            Id = 15,
                            ImageURL = "https://cdn-0.carsopedia.com/files/generations/Audi-D4-498.jpg",
                            ManufacturerId = 1,
                            ModelName = "S8+ D4.5",
                            YearCreated_End = 2018,
                            YearCreated_Start = 2015
                        },
                        new
                        {
                            Id = 16,
                            ImageURL = "https://www.auto-data.net/images/f4/file3193601.jpg",
                            ManufacturerId = 1,
                            ModelName = "S7 C7",
                            YearCreated_End = 2017,
                            YearCreated_Start = 2012
                        },
                        new
                        {
                            Id = 17,
                            ImageURL = "https://www.autocar.co.uk/sites/autocar.co.uk/files/audi-rs7_1.jpg",
                            ManufacturerId = 1,
                            ModelName = "RS7 C7",
                            YearCreated_End = 2019,
                            YearCreated_Start = 2013
                        },
                        new
                        {
                            Id = 18,
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/8/85/Audi_A6_S-line_%28C7%29_%E2%80%93_Frontansicht%2C_1._Mai_2012%2C_D%C3%BCsseldorf.jpg",
                            ManufacturerId = 1,
                            ModelName = "A6 C7",
                            YearCreated_End = 2018,
                            YearCreated_Start = 2011
                        },
                        new
                        {
                            Id = 19,
                            ImageURL = "https://mir-s3-cdn-cf.behance.net/project_modules/fs/b2ebb974237045.5c27acde184ed.jpg",
                            ManufacturerId = 1,
                            ModelName = "Q7 4L",
                            YearCreated_End = 2015,
                            YearCreated_Start = 2005
                        });
                });

            modelBuilder.Entity("RevTech.Data.Models.Vehicles.CarModelEngine", b =>
                {
                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.HasKey("CarModelId", "EngineId");

                    b.HasIndex("EngineId");

                    b.ToTable("CarModelsEngines");

                    b.HasData(
                        new
                        {
                            CarModelId = 1,
                            EngineId = 1
                        },
                        new
                        {
                            CarModelId = 2,
                            EngineId = 1
                        },
                        new
                        {
                            CarModelId = 3,
                            EngineId = 1
                        },
                        new
                        {
                            CarModelId = 3,
                            EngineId = 2
                        },
                        new
                        {
                            CarModelId = 1,
                            EngineId = 3
                        },
                        new
                        {
                            CarModelId = 2,
                            EngineId = 3
                        },
                        new
                        {
                            CarModelId = 4,
                            EngineId = 4
                        },
                        new
                        {
                            CarModelId = 1,
                            EngineId = 4
                        },
                        new
                        {
                            CarModelId = 1,
                            EngineId = 5
                        },
                        new
                        {
                            CarModelId = 8,
                            EngineId = 6
                        },
                        new
                        {
                            CarModelId = 5,
                            EngineId = 6
                        },
                        new
                        {
                            CarModelId = 6,
                            EngineId = 7
                        },
                        new
                        {
                            CarModelId = 7,
                            EngineId = 7
                        },
                        new
                        {
                            CarModelId = 9,
                            EngineId = 8
                        },
                        new
                        {
                            CarModelId = 19,
                            EngineId = 8
                        },
                        new
                        {
                            CarModelId = 10,
                            EngineId = 9
                        },
                        new
                        {
                            CarModelId = 11,
                            EngineId = 10
                        },
                        new
                        {
                            CarModelId = 12,
                            EngineId = 11
                        },
                        new
                        {
                            CarModelId = 16,
                            EngineId = 11
                        },
                        new
                        {
                            CarModelId = 13,
                            EngineId = 12
                        },
                        new
                        {
                            CarModelId = 17,
                            EngineId = 12
                        },
                        new
                        {
                            CarModelId = 14,
                            EngineId = 12
                        },
                        new
                        {
                            CarModelId = 15,
                            EngineId = 13
                        },
                        new
                        {
                            CarModelId = 6,
                            EngineId = 14
                        },
                        new
                        {
                            CarModelId = 7,
                            EngineId = 14
                        },
                        new
                        {
                            CarModelId = 9,
                            EngineId = 15
                        },
                        new
                        {
                            CarModelId = 19,
                            EngineId = 15
                        },
                        new
                        {
                            CarModelId = 19,
                            EngineId = 16
                        },
                        new
                        {
                            CarModelId = 18,
                            EngineId = 16
                        });
                });

            modelBuilder.Entity("RevTech.Data.Models.Vehicles.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Torque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Engines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HorsePower = 150,
                            Name = "1.8t",
                            Torque = 210
                        },
                        new
                        {
                            Id = 2,
                            HorsePower = 163,
                            Name = "1.8t",
                            Torque = 250
                        },
                        new
                        {
                            Id = 3,
                            HorsePower = 180,
                            Name = "1.8t",
                            Torque = 235
                        },
                        new
                        {
                            Id = 4,
                            HorsePower = 265,
                            Name = "2.7tt",
                            Torque = 362
                        },
                        new
                        {
                            Id = 5,
                            HorsePower = 250,
                            Name = "2.7tt",
                            Torque = 342
                        },
                        new
                        {
                            Id = 6,
                            HorsePower = 450,
                            Name = "4.2 FSI",
                            Torque = 430
                        },
                        new
                        {
                            Id = 7,
                            HorsePower = 354,
                            Name = "4.2 FSI",
                            Torque = 440
                        },
                        new
                        {
                            Id = 8,
                            HorsePower = 350,
                            Name = "4.2 FSI",
                            Torque = 440
                        },
                        new
                        {
                            Id = 9,
                            HorsePower = 200,
                            Name = "2.0 TFSI",
                            Torque = 280
                        },
                        new
                        {
                            Id = 10,
                            HorsePower = 211,
                            Name = "2.0 TFSI",
                            Torque = 350
                        },
                        new
                        {
                            Id = 11,
                            HorsePower = 420,
                            Name = "4.0 TFSI",
                            Torque = 600
                        },
                        new
                        {
                            Id = 12,
                            HorsePower = 560,
                            Name = "4.0 TFSI",
                            Torque = 700
                        },
                        new
                        {
                            Id = 13,
                            HorsePower = 605,
                            Name = "4.0 TFSI",
                            Torque = 700
                        },
                        new
                        {
                            Id = 14,
                            HorsePower = 333,
                            Name = "3.0 TFSI",
                            Torque = 440
                        },
                        new
                        {
                            Id = 15,
                            HorsePower = 290,
                            Name = "3.0 TFSI",
                            Torque = 420
                        },
                        new
                        {
                            Id = 16,
                            HorsePower = 310,
                            Name = "3.0 TFSI",
                            Torque = 440
                        });
                });

            modelBuilder.Entity("RevTech.Data.Models.Vehicles.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageURL = "https://w7.pngwing.com/pngs/115/486/png-transparent-audi-tt-car-volkswagen-group-audi-rs-6-audi-text-trademark-logo.png",
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            ImageURL = "https://w7.pngwing.com/pngs/986/859/png-transparent-mercedes-benz-u-s-international-car-daimler-ag-mercedes-benz-angle-trademark-logo.png",
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 3,
                            ImageURL = "https://image.similarpng.com/very-thumbnail/2020/06/Logo-bmw-vector-transparent-PNG.png",
                            Name = "BMW"
                        });
                });

            modelBuilder.Entity("RevTech.Data.User.UserVehicleConfiguration", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ConfigurationId");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("UserVehicleConfiguration");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.ECU_TCU_ConnectionTable", b =>
                {
                    b.HasOne("RevTech.Data.Models.PerformanceParts.ECUTuning", "ECUTuning")
                        .WithMany("TCUConnections")
                        .HasForeignKey("ECUTuningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevTech.Data.Models.PerformanceParts.TCUTuning", "TCUTuning")
                        .WithMany("TCUConnections")
                        .HasForeignKey("TCUTuningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ECUTuning");

                    b.Navigation("TCUTuning");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.ECUTuning", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.Engine", "Engine")
                        .WithMany("ECUTunings")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.ExhaustKit", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.Engine", "Engine")
                        .WithMany("ExhaustKits")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.FuelPump", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.Engine", "Engine")
                        .WithMany("FuelPumps")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.InjectorKit", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.Engine", "Engine")
                        .WithMany("InjectorKits")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.OilCooler", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.Engine", "Engine")
                        .WithMany("OilCoolers")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.SparkPlugs", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.Engine", "Engine")
                        .WithMany("SparkPlugs")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.SuperchargerKit", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.Engine", "Engine")
                        .WithMany("SuperchargerKits")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.TurboKit", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.Engine", "Engine")
                        .WithMany("TurboKits")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RevTech.Data.Models.UserConfiguration.UserConfiguration", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevTech.Data.Models.PerformanceParts.ECUTuning", "ECUTuning")
                        .WithMany()
                        .HasForeignKey("ECUTuningId");

                    b.HasOne("RevTech.Data.Models.PerformanceParts.ExhaustKit", "ExhaustKit")
                        .WithMany()
                        .HasForeignKey("ExhaustKitId");

                    b.HasOne("RevTech.Data.Models.PerformanceParts.FuelPump", "FuelPump")
                        .WithMany()
                        .HasForeignKey("FuelPumpId");

                    b.HasOne("RevTech.Data.Models.PerformanceParts.InjectorKit", "InjectorKit")
                        .WithMany()
                        .HasForeignKey("InjectorKitId");

                    b.HasOne("RevTech.Data.Models.PerformanceParts.OilCooler", "OilCooler")
                        .WithMany()
                        .HasForeignKey("OilCoolerId");

                    b.HasOne("RevTech.Data.Models.PerformanceParts.SparkPlugs", "SparkPlugs")
                        .WithMany()
                        .HasForeignKey("SparkPlugsId");

                    b.HasOne("RevTech.Data.Models.PerformanceParts.SuperchargerKit", "SuperchargerKit")
                        .WithMany()
                        .HasForeignKey("SuperchargerKitId");

                    b.HasOne("RevTech.Data.Models.PerformanceParts.TCUTuning", "TCUTuning")
                        .WithMany()
                        .HasForeignKey("TCUTuningId");

                    b.HasOne("RevTech.Data.Models.PerformanceParts.TurboKit", "TurboKit")
                        .WithMany()
                        .HasForeignKey("TurboKitId");

                    b.Navigation("CarModel");

                    b.Navigation("ECUTuning");

                    b.Navigation("ExhaustKit");

                    b.Navigation("FuelPump");

                    b.Navigation("InjectorKit");

                    b.Navigation("OilCooler");

                    b.Navigation("SparkPlugs");

                    b.Navigation("SuperchargerKit");

                    b.Navigation("TCUTuning");

                    b.Navigation("TurboKit");
                });

            modelBuilder.Entity("RevTech.Data.Models.Vehicles.CarModel", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.Manufacturer", "Manufacturer")
                        .WithMany("CarModel")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("RevTech.Data.Models.Vehicles.CarModelEngine", b =>
                {
                    b.HasOne("RevTech.Data.Models.Vehicles.CarModel", "CarModel")
                        .WithMany("CarModelEngines")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevTech.Data.Models.Vehicles.Engine", "Engine")
                        .WithMany("CarModelEngines")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RevTech.Data.User.UserVehicleConfiguration", b =>
                {
                    b.HasOne("RevTech.Data.Models.UserConfiguration.UserConfiguration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.ECUTuning", b =>
                {
                    b.Navigation("TCUConnections");
                });

            modelBuilder.Entity("RevTech.Data.Models.PerformanceParts.TCUTuning", b =>
                {
                    b.Navigation("TCUConnections");
                });

            modelBuilder.Entity("RevTech.Data.Models.Vehicles.CarModel", b =>
                {
                    b.Navigation("CarModelEngines");
                });

            modelBuilder.Entity("RevTech.Data.Models.Vehicles.Engine", b =>
                {
                    b.Navigation("CarModelEngines");

                    b.Navigation("ECUTunings");

                    b.Navigation("ExhaustKits");

                    b.Navigation("FuelPumps");

                    b.Navigation("InjectorKits");

                    b.Navigation("OilCoolers");

                    b.Navigation("SparkPlugs");

                    b.Navigation("SuperchargerKits");

                    b.Navigation("TurboKits");
                });

            modelBuilder.Entity("RevTech.Data.Models.Vehicles.Manufacturer", b =>
                {
                    b.Navigation("CarModel");
                });
#pragma warning restore 612, 618
        }
    }
}
